"""Add production tables and columns

Revision ID: 406258eeaf96
Revises: ffb05ebd62e7
Create Date: 2026-06-04 12:06:09.458453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406258eeaf96'
down_revision: Union[str, Sequence[str], None] = 'ffb05ebd62e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anniversaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('anniversary_date', sa.Date(), nullable=False),
    sa.Column('reminder_days_before', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], name=op.f('fk_anniversaries_partner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_anniversaries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anniversaries'))
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events'))
    )
    op.create_table('cloud_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cloud_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cloud_files'))
    )
    op.create_table('daily_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_goals'))
    )
    op.create_table('game_leaderboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_leaderboards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_leaderboards')),
    sa.UniqueConstraint('user_id', name=op.f('uq_game_leaderboards_user_id'))
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('board_state', sa.Text(), nullable=True),
    sa.Column('player1_id', sa.String(length=36), nullable=False),
    sa.Column('player2_id', sa.String(length=36), nullable=False),
    sa.Column('turn_player_id', sa.String(length=36), nullable=True),
    sa.Column('winner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_game_sessions_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], name=op.f('fk_game_sessions_player1_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], name=op.f('fk_game_sessions_player2_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_player_id'], ['users.id'], name=op.f('fk_game_sessions_turn_player_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_sessions'))
    )
    op.create_table('habits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('max_streak', sa.Integer(), nullable=True),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits'))
    )
    op.create_table('love_calculations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user1_id', sa.String(length=36), nullable=False),
    sa.Column('user2_id', sa.String(length=36), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], name=op.f('fk_love_calculations_user1_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], name=op.f('fk_love_calculations_user2_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_love_calculations'))
    )
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('note_type', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_notes_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_table('relationship_memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], name=op.f('fk_relationship_memories_partner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_relationship_memories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_memories'))
    )
    op.create_table('note_collaborators',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_collaborators_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_note_collaborators_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'user_id', name=op.f('pk_note_collaborators'))
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hidden_by_user_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poll_question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poll_options', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poll_votes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('qa_question', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('qa_answers', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hidden_chat_pin', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('music', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('movies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hobbies')
        batch_op.drop_column('movies')
        batch_op.drop_column('music')
        batch_op.drop_column('interests')
        batch_op.drop_column('hidden_chat_pin')
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('two_factor_enabled')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('qa_answers')
        batch_op.drop_column('qa_question')
        batch_op.drop_column('poll_votes')
        batch_op.drop_column('poll_options')
        batch_op.drop_column('poll_question')
        batch_op.drop_column('music_url')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('available_at')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('hidden_by_user_id')
        batch_op.drop_column('is_hidden')

    op.drop_table('note_collaborators')
    op.drop_table('relationship_memories')
    op.drop_table('notes')
    op.drop_table('love_calculations')
    op.drop_table('habits')
    op.drop_table('game_sessions')
    op.drop_table('game_leaderboards')
    op.drop_table('daily_goals')
    op.drop_table('cloud_files')
    op.drop_table('calendar_events')
    op.drop_table('anniversaries')
    # ### end Alembic commands ###
