"""add_backup_key_ciphertext

Revision ID: 709d83cc1849
Revises: f2d1bbb1669d
Create Date: 2026-06-04 12:29:25.016460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709d83cc1849'
down_revision: Union[str, Sequence[str], None] = 'f2d1bbb1669d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_key_ciphertext', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('backup_key_ciphertext')

    # ### end Alembic commands ###
