"""add_chat_sequences

Revision ID: 98ba96713717
Revises: 709d83cc1849
Create Date: 2026-06-04 12:37:57.724431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ba96713717'
down_revision: Union[str, Sequence[str], None] = '709d83cc1849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sequences',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_sequences_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_chat_sequences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_sequences')
    # ### end Alembic commands ###
