"""add_cto_master_columns_and_tables

Revision ID: f2d1bbb1669d
Revises: 406258eeaf96
Create Date: 2026-06-04 12:25:53.511320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d1bbb1669d'
down_revision: Union[str, Sequence[str], None] = '406258eeaf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('current_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_msg_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('message_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('message_sequence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_modified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_client_msg_id'), ['client_msg_id'], unique=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_opt_out', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')
        batch_op.drop_column('device_id')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('ai_opt_out')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_client_msg_id'))
        batch_op.drop_column('last_modified_at')
        batch_op.drop_column('message_sequence')
        batch_op.drop_column('message_status')
        batch_op.drop_column('client_msg_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('current_hash')
        batch_op.drop_column('previous_hash')

    op.drop_table('event_logs')
    # ### end Alembic commands ###
